server:
  servlet:
    context-path: /backend
service:
  # dns: https://sample-ecs-alb-1379155413.ap-northeast-1.elb.amazonaws.com/
   dns: internal-ma-akaogit-private-alb-1087251464.ap-northeast-1.elb.amazonaws.com/